### ISSUE TITLE
basic-account-viewer by BlackBadPinguin

### ISSUE THREAD

**Issue by BlackBadPinguin** [tyvdh/stellar-quest-bounties#108]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

 https://github.com/BlackBadPinguin/basic-account-viewer

hosted websited link : https://ntqv7.csb.app/

**Comment by hanseartic** [comment]
When getting around review-stage, you may want to include a PR to add a stellar address for your account to https://github.com/tyvdh/stellar-quest-bounties/blob/main/ADDRESSES.yml

**Comment by BlackBadPinguin** [comment]
oh indeed, thanks for the advice

**Comment by BlackBadPinguin** [comment]
still working on it, but the albedo sdk is really hard to understand, at least for me

**Comment by hanseartic** [comment]
If you opt to chose freighter it's much less complex. But you would need to do the 'login' a bit different as you can't sign a txt but rather transactions. Or you just opt to load the public key from the extensions and go with that as all the information you display is public anyways...

**Comment by BlackBadPinguin** [comment]
now everything should work, but I'm still working on hosting it with GitHub pages

**Comment by BlackBadPinguin** [comment]
if the hosting on codesandbox is enough it should be ready for review

**Comment by hanseartic** [comment]
The scrollin is somehow messed up. With many assets you can't see the top of the page anymore:
![grafik](https://user-images.githubusercontent.com/1752217/131198578-7d4d4915-f41f-444b-8130-842de5249e75.png)

**Comment by BlackBadPinguin** [comment]
That scrolling is odd, will look into it, also thanks for the advice with the stellar sdk, somehow I didn't now about it

**Comment by BlackBadPinguin** [comment]
i change the layout a bit, made it a bit easier , and now it should work

**Comment by ElliotFriend** [comment]
Looks like the functionality is right on, according to the specs. When I resize my browser, it seems to scroll fine. Works well on mobile, too!

Couple things I noticed:

- For me, pulling up the js console in my browser results in a bunch of these warnings: `Warning: Encountered two children with the same key, `SQ0205`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.` Looks like your key for the various balances `<li>`s is just the asset code. A minority of folks have assets from series 1 and 2 that are identical (color and monochrome badges). It's unlikely to be a huge issue, but you may want to add the index of the map operation in there to make them unique, just in case.
- I'm not a React guru, so I could be wrong here. For your last two pieces of information, `created_at` and `source_account`, you could likely skip the array map and go with something like this: `account[0].created_at` or `account[0].source_account`. Might make things a bit simpler for you?
- The bounty spec says your code should be licensed under an open source license. I may have missed it, but I didn't see one in your repository.

Overall, great work!

**Comment by BlackBadPinguin** [comment]
Hello Elliot, thanks for your response, I muted the Errors because as you said, it's just a minority. Also, I tried to not use the array map, but that somehow didn't work, I think react just wants an array for JSON parsing, but it's also my first React project so I really don't know. Last but not least I now added the License.

**Comment by BlackBadPinguin** [comment]
Can I now set the Status to review completed? Or do someone else have to give their approval?

**Comment by ElliotFriend** [comment]
Great question! The bounties are still a bit new, so we're kinda figuring things out as they go.

I'm happy to give my "official" stamp of approval. @hanseartic anything more to add to it?

Does @tyvdh have to give the final approval?

**Comment by hanseartic** [comment]
The code and result looks ok to me, too.
I have a few remarks left, still:
* UX
  * After being logged-in with albedo I'd rather expect a 'logout' button
  * If there are mutliple assets with the same name in an account (as for example in my screenshot above) you don't know which is which. Could be a nice addition to also show either the domain or the asset-isser. It was not part of the bounty spec but just something to conider for a real-life application.
* repo/code
  * I don't think you're supposed to put your own name into the license-file.
  * The `build`-folder is supposed to be `.gitignore`'d. I guess for the sake of simplicity to have it run in code-sandbox (I've never used it before) it could be an ok workaround. But in general that folder should be populated during a build-step (either on the local machine or as part of a pipeline, e.g. github actions)
  * The variables are function-local. So you there's no need to distinguish them by a counter: 
![grafik](https://user-images.githubusercontent.com/1752217/131617607-89e4d51d-592b-44af-aff8-2f2d163553ec.png)
  I'd either just use `res` again or choose a meaningful name like `payment_response`. But again this does not break anything - it's just about keeping the code clean and readable.
  
  Having said all of the above I would already be fine with `review done`. So you could just tick that box.

**Comment by BlackBadPinguin** [comment]
Thanks for your detailed response, I now renamed the variables, as well as adding the build folder to the gitignore.  I think the License needs my name because I'm the Copyright Holder, referring to https://opensource.org/licenses/MIT. I will look into the logout button and the asset issuer idea.

**Comment by ElliotFriend** [comment]
>I think the License needs my name because I'm the Copyright Holder, referring to https://opensource.org/licenses/MIT.

I've always had this same understanding of the MIT license, as well. At least, that's how I've used it and seen it used.

**Comment by tyvdh** [comment]
`d560148aa9214aebc2e3ada0d3df985425789b7a19e4f1e906318ead1a4aad42`
