### ISSUE TITLE
Federation server implementation

### ISSUE THREAD

**Issue by ralphilius** [tyvdh/stellar-quest-bounties#118]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/federation-server.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details
 - Repo: https://github.com/ralphilius/sqb-federation-server
 - Link to test:
   - UI: https://fs.ralphilius.com
   - API: https://fs.ralphilius.com/api/federation

**Comment by Kanaye** [comment]
As mentioned on discord:
Loggin in with github / discord redirects me to `https://github.com/codespaces/auth/ralphilius-sqb-federation-server-r96jgjrfwprg?port=3000&<redacted access token stuff>` after hitting supabase, so can't test further.
Haven't tried email login yet though.

The federation endpoint doesn't send back error content like mentioned in the [spec](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0002.md#federation-response)

e.g. `GET federation/` could return something like `{"error": "Missing parameters q and type"}` or similar.

Couldn't test yet the valid response because of the login issues mentioned above.

**Comment by Kanaye** [comment]
![login screen](https://user-images.githubusercontent.com/5108989/132103666-ed778e14-ff53-4f6b-ac63-7f0bdc2da160.png)
Just hitting the "sign in with magic-link"-button without entering an email address, shows a "success" message.
I'd expect some kind of "required field" error as ... good luck sending an email to "".

**Comment by ralphilius** [comment]
@Kanaye Thanks for feedback. I've provided fixes for below issues:

> The federation endpoint doesn't send back error content like mentioned in the spec

:white_check_mark: 

> Just hitting the "sign in with magic-link"-button without entering an email address, shows a "success" message.
I'd expect some kind of "required field" error as ... good luck sending an email to "".

:white_check_mark:

**Comment by rahimklaber** [comment]
Your toml file seems to be outdated, the federation server entry is set to a vercel endpoint. 

When going to `https://fs.ralphilius.com/.well-known/stellar.toml` a download prompt appears instead of showing rendering the toml in browser. While this doesn't go against the toml spec, I still think the toml response should be `text/plain` instead of `application/toml`, so that it can be rendered in the browser.

making a lookup request to the api still works when the `type` parameter is incorrect. For example : `https://fs.ralphilius.com/api/federation?q=YOUREEMAILHERE*fs.ralphilius.com&type=alkdjfaldf` does not give an error.

**Comment by LorDDark6660** [comment]
After click on github login button, redirect me to https://rlfvrtezidqemlcgvjfo.supabase.co/auth/v1/authorize?provider=github, but page don't load

**Comment by LorDDark6660** [comment]
After login with email, popup message mail was send, but email not arrived.
![Screenshot_2021-12-12-08-11-56-36_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/92062140/145703847-12faa4f8-7c1e-41f2-881c-d3405cd1f533.jpg)

**Comment by BlackBadPinguin** [comment]
Hello, would have liked to test your implementation, however, if I try to log in with discord I get forwarded to `https://rlfvrtezidqemlcgvjfo.supabase.co/auth/v1/authorize?provider=discord` which gives me an  `NAME_NOT_RESOLVED` Error.
same with GitHub. Also, the Email seems to never actually get sent out.

**Comment by ralphilius** [comment]
@BlackBadPinguin @LorDDark6660 My supabase instance was paused for inactivity. Let's try again since I've unpaused it.
Thanks

**Comment by ralphilius** [comment]
> Your toml file seems to be outdated, the federation server entry is set to a vercel endpoint.
> 
> When going to `https://fs.ralphilius.com/.well-known/stellar.toml` a download prompt appears instead of showing rendering the toml in browser. While this doesn't go against the toml spec, I still think the toml response should be `text/plain` instead of `application/toml`, so that it can be rendered in the browser.
> 
> making a lookup request to the api still works when the `type` parameter is incorrect. For example : `https://fs.ralphilius.com/api/federation?q=YOUREEMAILHERE*fs.ralphilius.com&type=alkdjfaldf` does not give an error.

These issues have been addressed. Could you continue review? Or is it done for you?

**Comment by BlackBadPinguin** [comment]
I know tested ur submission a bit and can say the following:

Sign In with Discord Works fine. ✅

Sign In with GitHub works fine. ✅

Sign In with Email works fine. ✅

Sign in with Albedo works, however, you need to reload the Page before it actually shows your PublicKey I would say that's a bit unintuitive. ✅

The Delete Account Button works. ✅

The API Querying for a type name works.✅

However, one thing I noticed is that according to spec the 404 error should respond with a 404 status code:
![131631910-05d44921-8973-4bfd-91a4-747bb39750b7](https://user-images.githubusercontent.com/34062375/150545187-38541338-c565-4ce2-92f8-3021d169116f.png)
whereas the service implemented here responds with a slightly different answer
[https://fs.ralphilius.com/api/federation](https://fs.ralphilius.com/api/federation)

You also have documentation on how to run the Server. ✅

So overall, the submission looks good :) , about the 404 error I'm not entirely sure that I understood the Spec correctly, so maybe the implementation is right, maybe not.

**Comment by rahimklaber** [comment]
I think its good to go. I don't think I had found issues aside from the ones I mentioned.

**Comment by BlackBadPinguin** [comment]
You might want to change the Label from review to reward, to finalize this bounty.

**Comment by ralphilius** [comment]
> You might want to change the Label from review to reward, to finalize this bounty.

Thanks. I've changed it.

**Comment by ElliotFriend** [comment]
`a04252903fd7291d2309b155e3acf7e59a8921ee755acaf6dd9ea98bda7a1d0d`
