### ISSUE TITLE
Basic Account Viewer by sohanrai

### ISSUE THREAD

**Issue by sohanrai** [tyvdh/stellar-quest-bounties#147]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/basic-account-viewer.md

### Mark your progress

- [X] 🔵&nbsp; Started working
- [X] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

### Provide relevant details

Repo: https://github.com/sohanrai/Basic-Account-Viewer-for-Stellar

Demo: https://sohanrai.github.io/Basic-Account-Viewer-for-Stellar/

**Comment by raeesnazeer** [comment]
Hello,

Please share the demo link.

**Comment by raeesnazeer** [comment]
Everything looks fine and works well, only one mistake is the freighter button when not installed goes to the rabet.io link, fix that and rest is good to go.

**Comment by sohanrai** [comment]
Yes, the issue is fixed.

**Comment by Kanaye** [comment]
I'd personally prefer to move the script to it's own file, just looks cleaner.
And to use either a DOM-Api (`document.createElement` and similar) to modify the DOM instead of `innerHTML`  as it doesn't leave your app open for XSS attacks. 
In this case it shouldn't matter much as the only user provided value is the asset code which got enough limitations to mitigate most if not all XSS attacks.
So I'll leave both decisions up to you ;)
Everything else looks good to me 👍

**Comment by tyvdh** [comment]
`eeb57db172e5d6db181bed72d8d61c08bba1401298f651505c1438c829205426`
