### ISSUE TITLE
Stellar Quest badge checker

### ISSUE THREAD

**Issue by rahimklaber** [tyvdh/stellar-quest-bounties#23]
### Link the bounty file

https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-quest-badge-checker.md

### Mark your progress

- [x] 🔵&nbsp; Started working
- [x] 🟢&nbsp; Ready for review
- [x] 🟣&nbsp; Review completed

Submission for #4.
Github repo : https://github.com/rahimklaber/stellar_quest_badge_checker

Let the roast begin.

**Comment by Kanaye** [comment]
Code styles are sometimes inconsistent e.g. [here](https://github.com/rahimklaber/stellar_quest_badge_checker/blob/e4066b6172a5232a49b8a9cbcad8974dbfb817f0/src/lib/createAttestation.ts#L26) or [here (sometime a space before a `{` sometimes not)](https://github.com/rahimklaber/stellar_quest_badge_checker/blob/e4066b6172a5232a49b8a9cbcad8974dbfb817f0/src/Badges.tsx#L26-L27)
I'd suggest adding [eslint](https://eslint.org/) and/or [prettier](https://prettier.io/) to also make contributions easier.

Also while it's not a problem for the usage, it's weird to export a pubnet horizon instance with the testnet network:
https://github.com/rahimklaber/stellar_quest_badge_checker/blob/e4066b6172a5232a49b8a9cbcad8974dbfb817f0/src/lib/stellar.ts#L3-L4

From a UX perspective: the contrast between the vistied and normal link colors on the card background is quite bad, especially for people with color-blindness:
![links](https://user-images.githubusercontent.com/5108989/127688341-179e7cb7-962b-4095-8234-a4b8314e1e87.png)

even worse is the 
> Powered by PQINA

message (I even missed that it's there 😂 )
![credit](https://user-images.githubusercontent.com/5108989/127688942-654db543-8df5-4367-8c83-e978289f899e.png)

Otherwise I like the UI 👍 , a loading screen while the badge images are loading would be nice, but nothing necessary.

So nothing major yet, but I still need to take a look at some of the verifing code ;P

**Comment by rahimklaber** [comment]
I will take a look at the text, did not consider that. I normally use nightlight turned to 100% so I don't notice somethings.

**Comment by rahimklaber** [comment]
Alright, I have improved a bunch:
* I ran a code formatter on the whole project, should be consistent now.
* I removed the random testnet variable
* I made the anchors consistent
* I removed the powered by message
* I removed some old todos

I'll take a look at adding eslint and prettier later.

**Comment by apaldiwal** [comment]
As the number of series grows, it will be difficult to show all the badges without scrolling. So, I was thinking if you could maybe add a vertical navigation bar to improve the UI? I really like the interface of [Credly's Acclaim](https://www.credly.com/organizations/acclaim/badges) website. 

I was thinking something along these lines but it is definitely not mandatory or important that you implement it. It's just my opinion. By the way, you did a great job. I really like the 'Connect with Albedo' -> 'Create Attestation' -> 'Valid Attestation' flow.

![image](https://user-images.githubusercontent.com/73634107/127706144-0d72936f-35a4-48aa-bccd-d0bc27c84c9c.png)

**Comment by rahimklaber** [comment]
> 1. As the number of series grows, it will be difficult to show all the badges without scrolling. So, I was thinking if you could maybe add a horizontal navigation bar to improve the UI?

I think scrolling is fine for now, when it gets to maybe Series 5 or 6 I might change it, but for now I like the layout. However, if more people agree with you I will change it.

Ty for the compliments.

**Comment by Kanaye** [comment]
As the badges are hardcoded, someone will need to update the tool to work with future series anyways. So the design can be updated when adding the badges ;)

**Comment by rahimklaber** [comment]
Btw, what do you guys think about the level of comments. Do you think I should add more comments?

**Comment by Smephite** [comment]
It seems like you forgot to include the mono badges. 
You have a list of all valid quest assets here: https://quest.stellar.org/.well-known/stellar.toml

**Comment by rahimklaber** [comment]
I actually did not include them on purpose.

**Comment by Smephite** [comment]
I guess the purpose of this application is to prove that you completed the quests / put effort into learning the eco system thus it should not matter at which time you completed the quests

**Comment by rahimklaber** [comment]
👍 will do.

**Comment by apaldiwal** [comment]
> Btw, what do you guys think about the level of comments. Do you think I should add more comments?

If you want to you can. It's not a big project as of now, so it's easy to understand the code.

**Comment by rahimklaber** [comment]
I've added support for monochrome badges. 

This is what it looks like
![image](https://user-images.githubusercontent.com/21971137/127754247-687bee3b-de1f-4e09-a5da-3f161d9111e1.png)

**Comment by hanseartic** [comment]
Please create a new PR to add a link to your submission into https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-2/stellar-quest-badge-checker.md

**Comment by tyvdh** [comment]
@Kanaye 
@apaldiwal 
Are we happy with the review of this bounty? It's looking pretty 🔥  to me, any final thoughts or are we ready for payout?

**Comment by Kanaye** [comment]
The only open (and I need to admit: not yet reported) thing I've got is that the page makes an invalid request on page load to horizon `https://horizon.stellar.org/accounts/`.
I guess the page tries to load the users account without having the public key.

Otherwise it looks good to me 👍

**Comment by rahimklaber** [comment]
👍 I've fixed the error.
